export RUNNING_MODE=unittest

export REACT_APP_FB_API_KEY=$FB_API_KEY
export REACT_APP_FB_AUTH_DOMAIN=$FB_AUTH_DOMAIN
export REACT_APP_FB_DB_URL=$FB_DB_URL
export REACT_APP_FB_PROJ_ID=$FB_PROJ_ID
export REACT_APP_FB_BUCKET=$FB_BUCKET
export REACT_APP_FB_MSG_ID=$FB_MSG_ID
export REACT_APP_FB_APP_ID=$FB_APP_ID
export REACT_APP_RUNNING_MODE=$RUNNING_MODE

export STORYBOOK_FB_API_KEY=$FB_API_KEY
export STORYBOOK_FB_AUTH_DOMAIN=$FB_AUTH_DOMAIN
export STORYBOOK_FB_DB_URL=$FB_DB_URL
export STORYBOOK_FB_PROJ_ID=$FB_PROJ_ID
export STORYBOOK_FB_BUCKET=$FB_BUCKET
export STORYBOOK_FB_MSG_ID=$FB_MSG_ID
export STORYBOOK_FB_APP_ID=$FB_APP_ID
export STORYBOOK_RUNNING_MODE=$RUNNING_MODE