export FB_API_KEY=[...]
export FB_AUTH_DOMAIN=[...]
export FB_DB_URL=[...]
export FB_PROJ_ID=[...]
export FB_BUCKET=[...]
export FB_MSG_ID=[...]
export FB_APP_ID=[...]

export REACT_APP_FB_API_KEY=$FB_API_KEY
export REACT_APP_FB_AUTH_DOMAIN=$FB_AUTH_DOMAIN
export REACT_APP_FB_DB_URL=$FB_DB_URL
export REACT_APP_FB_PROJ_ID=$FB_PROJ_ID
export REACT_APP_FB_BUCKET=$FB_BUCKET
export REACT_APP_FB_MSG_ID=$FB_MSG_ID
export REACT_APP_FB_APP_ID=$FB_APP_ID

export STORYBOOK_FB_API_KEY=$FB_API_KEY
export STORYBOOK_FB_AUTH_DOMAIN=$FB_AUTH_DOMAIN
export STORYBOOK_FB_DB_URL=$FB_DB_URL
export STORYBOOK_FB_PROJ_ID=$FB_PROJ_ID
export STORYBOOK_FB_BUCKET=$FB_BUCKET
export STORYBOOK_FB_MSG_ID=$FB_MSG_ID
export STORYBOOK_FB_APP_ID=$FB_APP_ID